export {
  CORE_API_ENDPOINTS,
  AGENT_READY_ENDPOINTS,
  agentReadyEndpoints,
  partialEndpoints,
  excludedEndpoints,
  agentReadyIdempotentEndpoints,
  agentReadyEmailEndpoints,
  readinessSummary,
  endpointKey,
  type ApiEndpointEntry,
  type AgentReadiness,
  type AgentReadinessGap,
  type ErrorEnvelope,
  type HttpMethod,
} from "./manifest";
