/**
 * PICT model (#1188, census docs/PICT_CENSUS.md § S9): POST
 * /api/eduai/generate-questions (../../src/routes/eduai.js) forks on the
 * platform-role flat gate, required-field validation, numQuestions vs
 * config.maxQuestions, and content-aware course access — then, once
 * admitted, forwards numQuestions/mcqRequiredChoiceCount/distributions
 * downstream unchanged (defaulted or clamped). One oracle
 * (tests/models/generate-questions.oracle.ts), one committed row table
 * (tests/models/generate-questions.cases.json, generated by
 * `npm run test:pict:gen` from tests/models/generate-questions.pict), and
 * one world-builder here, reusing tests/integration/eduaiRouteCoverage.integration.test.js's
 * established mocking (no DB / live Core; eduaiService and course-code
 * access resolution are mocked).
 */
import { vi, describe, it, expect, beforeEach, afterEach } from 'vitest';
import request from 'supertest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const { mockFindCoursesByProjectedCode, mockEnrollments, eduaiService } = vi.hoisted(() => ({
  mockFindCoursesByProjectedCode: vi.fn(),
  mockEnrollments: vi.fn(),
  eduaiService: { chat: vi.fn(), generateQuestions: vi.fn() },
}));

vi.mock('../../src/services/authService.js', () => ({ findOrCreateUser: vi.fn().mockResolvedValue({}) }));

vi.mock('../../src/config/settings.js', () => {
  const cfg = {
    coreUrl: 'http://core.test',
    eduaiApiKey: 'k',
    corsOrigins: ['*'],
    nodeEnv: 'test',
    logLevel: 'silent',
    maxQuestions: 50,
  };
  return { config: cfg, default: cfg };
});

vi.mock('../../src/services/courseListService.js', () => ({
  findCoursesByProjectedCode: mockFindCoursesByProjectedCode,
}));

vi.mock('../../src/services/coreApiService.js', () => ({
  getCourseEnrollmentsFromCore: mockEnrollments,
  getCourseFromCore: vi.fn().mockResolvedValue({ id: 'cuid-core-course', department: 'COSC' }),
  getMyProfileFromCore: vi.fn().mockResolvedValue({ authorizedUnits: [] }),
}));

vi.mock('../../src/services/eduaiService.js', () => ({ default: eduaiService }));

const { default: app } = await import('../../src/app.js');

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../../../../..');
const rows = JSON.parse(readFileSync(path.join(repoRoot, 'tests/models/generate-questions.cases.json'), 'utf8'));
const {
  generateQuestionsOracle,
  MAX_QUESTIONS,
  VALID_NUM_QUESTIONS,
  EXCEEDING_NUM_QUESTIONS,
  MCQ_INPUT,
  PROVIDED_DIFFICULTY_DISTRIBUTION,
  PROVIDED_REASONING_DISTRIBUTION,
} = await import(path.join(repoRoot, 'tests/models/generate-questions.oracle.ts'));

const INSTRUCTOR = { id: 'inst-1', role: 'INSTRUCTOR', email: 'i@t.co', name: 'I' };
const STUDENT = { id: 'stu-1', role: 'STUDENT', email: 's@t.co', name: 'S' };

function authAs(user) {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({ ok: true, json: () => Promise.resolve({ user }) }));
}

function accessibleCourse() {
  const course = { id: 1, userId: INSTRUCTOR.id, coreCourseId: 'cuid-core-course', code: null };
  mockFindCoursesByProjectedCode.mockResolvedValue([course]);
  mockEnrollments.mockResolvedValue({ enrollments: [{ studentId: INSTRUCTOR.id, role: 'INSTRUCTOR', isActive: true }] });
}

beforeEach(() => vi.clearAllMocks());
afterEach(() => vi.restoreAllMocks());

function buildBody(row) {
  const body = {};
  if (row.PromptPresent === 'yes') body.prompt = 'Write questions about recursion';
  if (row.CourseCodePresent === 'yes') body.courseCode = 'COSC 101';
  if (row.NumQuestions === 'valid') body.numQuestions = VALID_NUM_QUESTIONS;
  if (row.NumQuestions === 'exceeds') body.numQuestions = EXCEEDING_NUM_QUESTIONS;
  const mcq = MCQ_INPUT[row.Mcq];
  if (mcq !== undefined) body.mcqRequiredChoiceCount = mcq;
  if (row.DifficultyDistribution === 'provided') body.difficultyDistribution = PROVIDED_DIFFICULTY_DISTRIBUTION;
  if (row.ReasoningDistribution === 'provided') body.reasoningDistribution = PROVIDED_REASONING_DISTRIBUTION;
  return body;
}

describe.each(rows.map((row, index) => ({ row, index })))(
  'generate-questions PICT row #$index',
  ({ row }) => {
    it('matches the oracle', async () => {
      authAs(row.Authorized === 'yes' ? INSTRUCTOR : STUDENT);
      if (row.CourseAccess === 'yes') accessibleCourse();
      else mockFindCoursesByProjectedCode.mockResolvedValue([]);
      eduaiService.generateQuestions.mockResolvedValue([{ id: 'q1' }]);

      const res = await request(app)
        .post('/api/eduai/generate-questions')
        .set('Cookie', 'session=v')
        .send(buildBody(row));

      const expected = generateQuestionsOracle(row);
      expect(res.status).toBe(expected.status);

      if (expected.status === 200) {
        expect(res.status).toBe(200);
        const call = eduaiService.generateQuestions.mock.calls[0][0];
        expect(call.numQuestions).toBe(expected.forwarded.numQuestions);
        if (expected.forwarded.mcqRequiredChoiceCount === undefined) {
          expect(call).not.toHaveProperty('mcqRequiredChoiceCount');
        } else {
          expect(call.mcqRequiredChoiceCount).toBe(expected.forwarded.mcqRequiredChoiceCount);
        }
        expect(call.difficultyDistribution).toEqual(expected.forwarded.difficultyDistribution);
        expect(call.reasoningDistribution).toEqual(expected.forwarded.reasoningDistribution);
      }
    });
  },
);

it('sanity: MAX_QUESTIONS matches the mocked config.maxQuestions', () => {
  expect(MAX_QUESTIONS).toBe(50);
});
