/**
 * PICT model (#1188, census docs/PICT_CENSUS.md § S9): `findBestBankMetadataForSlot`
 * + `scoreMetadataMatch` (../../src/services/assessmentVariantService.js,
 * ../../src/services/assessmentVariantMetadataScoring.js) picks the
 * best-scoring bank question for a baseline exam slot, against a 75-point
 * cutoff and an already-used exclusion set.
 *
 * One oracle (tests/models/metadata-similarity-assembly.oracle.ts), one
 * committed row table (tests/models/metadata-similarity-assembly.cases.json,
 * generated by `npm run test:pict:gen` from
 * tests/models/metadata-similarity-assembly.pict), and one world-builder
 * here. Real Postgres via the QM Prisma client (TEST_DATABASE_URL) —
 * `findBestBankMetadataForSlot` only reads the bank from the DB; the
 * baseline `slotVariant` it scores against is a plain object, no DB row
 * needed for it.
 */
import { describe, it, expect, beforeAll, beforeEach, afterAll } from 'vitest';
import { createId } from '@paralleldrive/cuid2';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const hasTestDb = Boolean(process.env.TEST_DATABASE_URL);
const describeDb = hasTestDb ? describe : describe.skip;

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../../../../..');
const rows = JSON.parse(
  readFileSync(path.join(repoRoot, 'tests/models/metadata-similarity-assembly.cases.json'), 'utf8'),
);
const { metadataSimilarityAssemblyOracle } = await import(
  path.join(repoRoot, 'tests/models/metadata-similarity-assembly.oracle.ts')
);

const SLOT_TYPE = 'SA';
const SLOT_DIFFICULTY = 'medium';
const SLOT_REASONING = 'factual';
const OTHER_TYPE = 'MCQ';
const OTHER_DIFFICULTY = 'hard';
const OTHER_REASONING = 'application';

describeDb('metadata-similarity-assembly (PICT)', () => {
  let connectTestDatabase, truncateTestDatabase, prisma;
  let findBestBankMetadataForSlot;

  const USER = { id: 'cuid-msa-user', email: 'msa@test.com', name: 'MSA User' };

  beforeAll(async () => {
    const testDb = await import('../helpers/testDb.js');
    ({ connectTestDatabase, truncateTestDatabase, prisma } = testDb);
    await connectTestDatabase();

    ({ findBestBankMetadataForSlot } = await import('../../src/services/assessmentVariantService.js'));
  });

  afterAll(async () => {
    if (prisma) await prisma.$disconnect();
  });

  // A bare course + two topics, deliberately NOT using seedCoursesFixture.js
  // — that fixture also creates its own sample bank questions in the same
  // course, which would compete with (and sometimes outscore) the rows this
  // model constructs, making "best candidate" nondeterministic.
  let courseId, slotTopicId, otherTopicId;

  beforeEach(async () => {
    await truncateTestDatabase();
    await prisma.user.create({ data: { id: USER.id, email: USER.email, name: USER.name } });
    const course = await prisma.course.create({ data: { userId: USER.id, coreCourseId: `core-${randomUUID()}` } });
    courseId = course.id;
    const slotTopic = await prisma.topics.create({ data: { id: createId(), name: 'Slot Topic', courseId } });
    slotTopicId = slotTopic.id;
    const otherTopic = await prisma.topics.create({ data: { id: createId(), name: 'Other Topic', courseId } });
    otherTopicId = otherTopic.id;
  });

  /** A bank `questionMetadata` row with one non-draft variant, matching the slot on exactly the given dimensions. */
  async function makeBankCandidate({ topicMatch, typeMatch, difficultyMatch, reasoningMatch }) {
    const meta = await prisma.questionMetadata.create({
      data: {
        courseId,
        primaryTopicId: topicMatch ? slotTopicId : otherTopicId,
        type: typeMatch ? SLOT_TYPE : OTHER_TYPE,
        questionOrder: {},
      },
    });
    await prisma.variants.create({
      data: {
        questionMetadataId: meta.id,
        questionText: `Bank variant for ${meta.id}`,
        difficulty: difficultyMatch ? SLOT_DIFFICULTY : OTHER_DIFFICULTY,
        reasoningLevel: reasoningMatch ? SLOT_REASONING : OTHER_REASONING,
        isDraft: false,
        isAiGenerated: false,
        secondaryTopicsId: [],
        assessmentId: null,
      },
    });
    return meta;
  }

  describe.each(rows.map((row, index) => ({ row, index })))(
    'row #$index $row.TopicMatch/$row.TypeMatch/$row.DifficultyMatch/$row.ReasoningMatch/$row.AlreadyUsed/$row.HasFallback',
    ({ row }) => {
      it('matches the oracle', async () => {
        const primary = await makeBankCandidate({
          topicMatch: row.TopicMatch === 'yes',
          typeMatch: row.TypeMatch === 'yes',
          difficultyMatch: row.DifficultyMatch === 'yes',
          reasoningMatch: row.ReasoningMatch === 'yes',
        });

        let fallback = null;
        if (row.HasFallback === 'yes') {
          fallback = await makeBankCandidate({
            topicMatch: true,
            typeMatch: true,
            difficultyMatch: true,
            reasoningMatch: true,
          });
        }

        const usedBankMetadataIds = new Set(row.AlreadyUsed === 'yes' ? [primary.id] : []);
        const slotVariant = {
          questionMetadata: { primaryTopicId: slotTopicId, type: SLOT_TYPE },
          difficulty: SLOT_DIFFICULTY,
          reasoningLevel: SLOT_REASONING,
        };

        const result = await findBestBankMetadataForSlot(slotVariant, courseId, usedBankMetadataIds, prisma);
        const expected = metadataSimilarityAssemblyOracle(row);

        if (!expected.found) {
          expect(result).toBeNull();
        } else {
          expect(result).not.toBeNull();
          expect(result.score).toBe(expected.score);
          expect(result.questionMetadataId).toBe(expected.winner === 'fallback' ? fallback.id : primary.id);
        }
      });
    },
  );
});
