/**
 * PICT model (#1188, census docs/PICT_CENSUS.md § S9): PUT
 * /api/questions/variants/:variantId (../../src/routes/variants.js) forks on
 * course-access rank, current draft state, variant ownership, the requested
 * isDraft value, and which fields the request touches (the nine-field
 * aiTagOnly allowlist). One oracle (tests/models/variant-lifecycle-put.oracle.ts),
 * one committed row table (tests/models/variant-lifecycle-put.cases.json,
 * generated by `npm run test:pict:gen` from
 * tests/models/variant-lifecycle-put.pict), and one world-builder here.
 *
 * No DB / live Core, matching tests/integration/variantRbac.test.js's
 * established pattern for this route: questionService, coreWiringService,
 * and the RBAC Core reads (coreApiService) are mocked; the caller's Core
 * enrollment role drives the resolved course-access level, and the session
 * role drives the QM_AUTHORIZED flat gate. Shared cases/oracle loading comes
 * from tests/helpers/pictModel.js; shared auth/settings/coreApiService mocks
 * come from tests/helpers/pictRouteMocks.js; the row-runner (describe.each +
 * request + status assertion) comes from tests/helpers/pictRouteRunner.js
 * (#1188).
 */
import { vi, beforeEach, expect } from 'vitest';
import { loadPictModel } from '../helpers/pictModel.js';
import { stubSessionUser, stubEnrollment } from '../helpers/pictRouteMocks.js';
import { describePictRoute } from '../helpers/pictRouteRunner.js';

const { mockUpdateVariant, mockVariantsFindOne, mockEnrollments } = vi.hoisted(() => ({
  mockUpdateVariant: vi.fn(),
  mockVariantsFindOne: vi.fn(),
  mockEnrollments: vi.fn(),
}));

// Dynamic imports (rather than a static import used directly in the factory)
// because vi.mock factories run before the module's own static imports are
// wired up — see tests/helpers/pictRouteMocks.js.
vi.mock('../../src/services/authService.js', async () => {
  const { mockAuthService } = await import('../helpers/pictRouteMocks.js');
  return mockAuthService();
});

vi.mock('../../src/config/settings.js', async () => {
  const { mockSettings } = await import('../helpers/pictRouteMocks.js');
  return mockSettings();
});

vi.mock('../../src/services/questionService.js', () => ({
  createVariant: vi.fn(),
  updateVariant: mockUpdateVariant,
  deleteVariant: vi.fn(),
  getVariantsByQuestion: vi.fn(),
}));

vi.mock('../../src/services/coreWiringService.js', () => ({
  pushVariantToCore: vi.fn(),
  VALID_DIFFICULTIES: ['EASY', 'MEDIUM', 'HARD'],
  VALID_REASONING_LEVELS: ['LOW', 'MEDIUM', 'HIGH'],
}));

vi.mock('../../src/services/coreApiService.js', async () => {
  const { mockCoreApiService } = await import('../helpers/pictRouteMocks.js');
  return mockCoreApiService(mockEnrollments, { patchQuestionTestableOnCore: vi.fn() });
});

vi.mock('../../src/config/database.js', () => ({
  prisma: {
    variants: { findUnique: mockVariantsFindOne, update: vi.fn() },
    questionMetadata: {},
    assessments: {},
    assessmentSections: {},
    course: {},
    topics: { updateMany: vi.fn() },
  },
}));

const { default: app } = await import('../../src/app.js');

const { rows, oracle } = await loadPictModel('variant-lifecycle-put');
const { variantLifecyclePutOracle } = oracle;

// A genuine course-level TA is platform-role INSTRUCTOR (QM_AUTHORIZED
// excludes STUDENT/TA at the flat gate) who does NOT own the course and
// holds a Core enrollment with role 'TA' — resolveCourseAccess reads the
// enrollment role, not the platform role, once past the flat gate.
const COURSE = { id: 1, userId: 'owner-1', coreCourseId: 'cuid-core-course' };
const TA_USER = { id: 'ta-1', email: 'ta@test.com', role: 'INSTRUCTOR', name: 'Tee Ay' };
const INSTRUCTOR_PLUS_USER = { id: COURSE.userId, email: 'owner@test.com', role: 'INSTRUCTOR', name: 'Owner' };

function authAs(user, enrollRole) {
  stubSessionUser(user);
  stubEnrollment(mockEnrollments, user.id, enrollRole);
}

function loadVariant({ isDraft, createdBy }) {
  mockVariantsFindOne.mockResolvedValue({
    id: 42,
    isDraft,
    createdBy,
    questionMetadata: { type: 'SA', course: COURSE },
  });
}

beforeEach(() => {
  vi.clearAllMocks();
});

/** approved (isDraft:false) → draft (isDraft:true): the un-review transition. */
function isUnreviewing(row) {
  return row.CurrentIsDraft === 'approved' && row.RequestedIsDraft === 'true';
}

/** Body per FieldChangeKind + RequestedIsDraft — mirrors the nine-field aiTagOnly allowlist. */
function buildBody(row) {
  const body = {};
  if (row.RequestedIsDraft !== 'absent') body.isDraft = row.RequestedIsDraft === 'true';
  if (row.FieldChangeKind === 'content') body.questionText = 'Edited content';
  if (row.FieldChangeKind === 'onlyAiTag') body.isAiGenerated = true;
  return body;
}

function setupRow(row) {
  const isDraft = row.CurrentIsDraft === 'draft';
  const createdBy = row.AccessLevel === 'ta' ? (row.Ownership === 'own' ? TA_USER.id : 'someone-else') : 'anyone';
  loadVariant({ isDraft, createdBy });

  // #1080: un-reviewing (approved -> draft) clears coreQuestionId in the real
  // updateVariant so the next approval re-pushes to Core. Everywhere else,
  // coreQuestionId is already linked so an isDraft:false approval never trips
  // the route's Core-push branch — out of scope for this route-gate model.
  const unreviewing = isUnreviewing(row);
  mockUpdateVariant.mockResolvedValue({
    id: 42,
    isDraft: unreviewing ? true : false,
    coreQuestionId: unreviewing ? null : 'already-linked',
    questionMetadata: { course: COURSE },
  });

  if (row.AccessLevel === 'ta') {
    authAs(TA_USER, 'TA');
  } else {
    authAs(INSTRUCTOR_PLUS_USER, 'INSTRUCTOR');
  }

  return buildBody(row);
}

/** Confirms the un-review transition actually clears coreQuestionId in the response. */
async function verify({ row, res, expected }) {
  if (expected.status !== 200 || !isUnreviewing(row)) return;
  expect(res.body.data.coreQuestionId).toBeNull();
}

describePictRoute('variant-lifecycle-put', {
  app,
  rows,
  method: 'put',
  path: '/api/questions/variants/42',
  setupRow,
  oracle: variantLifecyclePutOracle,
  verify,
  label: (row) => `${row.AccessLevel}/${row.CurrentIsDraft}/${row.Ownership}/${row.RequestedIsDraft}/${row.FieldChangeKind}`,
});
