/**
 * PICT model (#1188, census docs/PICT_CENSUS.md § S9): PUT
 * /api/questions/variants/:variantId (../../src/routes/variants.js) forks on
 * course-access rank, current draft state, variant ownership, the requested
 * isDraft value, and which fields the request touches (the nine-field
 * aiTagOnly allowlist). One oracle (tests/models/variant-lifecycle-put.oracle.ts),
 * one committed row table (tests/models/variant-lifecycle-put.cases.json,
 * generated by `npm run test:pict:gen` from
 * tests/models/variant-lifecycle-put.pict), and one world-builder here.
 *
 * No DB / live Core, matching tests/integration/variantRbac.test.js's
 * established pattern for this route: questionService, coreWiringService,
 * and the RBAC Core reads (coreApiService) are mocked; the caller's Core
 * enrollment role drives the resolved course-access level, and the session
 * role drives the QM_AUTHORIZED flat gate.
 */
import { vi, describe, it, expect, beforeEach } from 'vitest';
import request from 'supertest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const { mockUpdateVariant, mockVariantsFindOne, mockEnrollments } = vi.hoisted(() => ({
  mockUpdateVariant: vi.fn(),
  mockVariantsFindOne: vi.fn(),
  mockEnrollments: vi.fn(),
}));

vi.mock('../../src/services/authService.js', () => ({
  findOrCreateUser: vi.fn().mockResolvedValue({}),
}));

vi.mock('../../src/config/settings.js', () => {
  const cfg = { coreUrl: 'http://core.test', eduaiApiKey: 'k', corsOrigins: ['*'], nodeEnv: 'test', logLevel: 'silent' };
  return { config: cfg, default: cfg };
});

vi.mock('../../src/services/questionService.js', () => ({
  createVariant: vi.fn(),
  updateVariant: mockUpdateVariant,
  deleteVariant: vi.fn(),
  getVariantsByQuestion: vi.fn(),
}));

vi.mock('../../src/services/coreWiringService.js', () => ({
  pushVariantToCore: vi.fn(),
  VALID_DIFFICULTIES: ['EASY', 'MEDIUM', 'HARD'],
  VALID_REASONING_LEVELS: ['LOW', 'MEDIUM', 'HIGH'],
}));

vi.mock('../../src/services/coreApiService.js', () => ({
  getCourseEnrollmentsFromCore: mockEnrollments,
  getCourseFromCore: vi.fn().mockResolvedValue({ id: 'cuid-core-course', department: 'COSC' }),
  getMyProfileFromCore: vi.fn().mockResolvedValue({ authorizedUnits: [] }),
  patchQuestionTestableOnCore: vi.fn(),
}));

vi.mock('../../src/config/database.js', () => ({
  prisma: {
    variants: { findUnique: mockVariantsFindOne, update: vi.fn() },
    questionMetadata: {},
    assessments: {},
    assessmentSections: {},
    course: {},
    topics: { updateMany: vi.fn() },
  },
}));

const { default: app } = await import('../../src/app.js');

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../../../../..');
const rows = JSON.parse(readFileSync(path.join(repoRoot, 'tests/models/variant-lifecycle-put.cases.json'), 'utf8'));
const { variantLifecyclePutOracle } = await import(
  path.join(repoRoot, 'tests/models/variant-lifecycle-put.oracle.ts')
);

// A genuine course-level TA is platform-role INSTRUCTOR (QM_AUTHORIZED
// excludes STUDENT/TA at the flat gate) who does NOT own the course and
// holds a Core enrollment with role 'TA' — resolveCourseAccess reads the
// enrollment role, not the platform role, once past the flat gate.
const COURSE = { id: 1, userId: 'owner-1', coreCourseId: 'cuid-core-course' };
const TA_USER = { id: 'ta-1', email: 'ta@test.com', role: 'INSTRUCTOR', name: 'Tee Ay' };
const INSTRUCTOR_PLUS_USER = { id: COURSE.userId, email: 'owner@test.com', role: 'INSTRUCTOR', name: 'Owner' };

function authAs(user, enrollRole) {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({ ok: true, json: () => Promise.resolve({ user }) }));
  mockEnrollments.mockResolvedValue({
    enrollments: enrollRole ? [{ studentId: user.id, role: enrollRole, isActive: true }] : [],
  });
}

function loadVariant({ isDraft, createdBy }) {
  mockVariantsFindOne.mockResolvedValue({
    id: 42,
    isDraft,
    createdBy,
    questionMetadata: { type: 'SA', course: COURSE },
  });
}

beforeEach(() => {
  vi.clearAllMocks();
  // coreQuestionId is already set so an isDraft:false approval never trips
  // the Core-push branch — out of scope for this route-gate model.
  mockUpdateVariant.mockResolvedValue({ id: 42, isDraft: false, coreQuestionId: 'already-linked', questionMetadata: { course: COURSE } });
});

/** Body per FieldChangeKind + RequestedIsDraft — mirrors the nine-field aiTagOnly allowlist. */
function buildBody(row) {
  const body = {};
  if (row.RequestedIsDraft !== 'absent') body.isDraft = row.RequestedIsDraft === 'true';
  if (row.FieldChangeKind === 'content') body.questionText = 'Edited content';
  if (row.FieldChangeKind === 'onlyAiTag') body.isAiGenerated = true;
  return body;
}

describe.each(rows.map((row, index) => ({ row, index })))(
  'variant-lifecycle-put PICT row #$index $row.AccessLevel/$row.CurrentIsDraft/$row.Ownership/$row.RequestedIsDraft/$row.FieldChangeKind',
  ({ row }) => {
    it('matches the oracle', async () => {
      const isDraft = row.CurrentIsDraft === 'draft';
      const createdBy = row.AccessLevel === 'ta' ? (row.Ownership === 'own' ? TA_USER.id : 'someone-else') : 'anyone';
      loadVariant({ isDraft, createdBy });

      if (row.AccessLevel === 'ta') {
        authAs(TA_USER, 'TA');
      } else {
        authAs(INSTRUCTOR_PLUS_USER, null);
      }

      const res = await request(app)
        .put('/api/questions/variants/42')
        .set('Cookie', 'session=v')
        .send(buildBody(row));

      const expected = variantLifecyclePutOracle(row);
      expect(res.status).toBe(expected.status);
    });
  },
);
