/**
 * PICT model (#1188, census docs/PICT_CENSUS.md § S9): the deterministic
 * scoring pipeline inside `reviewVariantExamWithAi`
 * (../../src/services/assessmentVariantService.js:1117-1226) — composite
 * rubric weighting, distinctness factor, and the usability multiplier's two
 * different gates (always-applied per-question vs toggle-gated exam-level).
 * The AI judge call itself is mocked; this model is only the arithmetic
 * applied to whatever rubric scores come back.
 *
 * One oracle (tests/models/ai-judge-scoring.oracle.ts), one committed row
 * table (tests/models/ai-judge-scoring.cases.json, generated by
 * `npm run test:pict:gen` from tests/models/ai-judge-scoring.pict). Shared
 * cases/oracle loading comes from tests/helpers/pictModel.js (#1188).
 */
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { loadPictModel } from '../helpers/pictModel.js';

const chat = vi.fn();
const findOne = vi.fn();
const enrichCourseDetail = vi.fn();
const loadOrderedVariantsForAssessment = vi.fn();

vi.mock('../../src/services/eduaiService.js', () => ({
  default: { isConfigured: () => true, chat },
}));

vi.mock('../../src/config/database.js', () => ({
  prisma: {
    assessments: { findFirst: findOne },
    assessmentSections: {},
    sectionVariants: {},
    variants: {},
    questionMetadata: {},
    course: {},
    topics: {},
    variantSelectionCursor: {},
  },
}));

vi.mock('../../src/services/courseListService.js', () => ({
  enrichCourseDetail,
  formatSemesterDisplay: vi.fn(),
  deriveSemesterDisplayForCourseId: vi.fn(),
}));

vi.mock('../../src/services/assessmentVariantUtils.js', () => ({
  loadOrderedVariantsForAssessment,
  aggregateStructure: vi.fn(),
}));

vi.mock('../../src/services/assessmentVariantMetadataScoring.js', () => ({
  scoreMetadataMatch: vi.fn(),
}));

const { reviewVariantExamWithAi } = await import('../../src/services/assessmentVariantService.js');

const { rows, oracle } = await loadPictModel('ai-judge-scoring');
const { aiJudgeScoringOracle } = oracle;

const LEVEL_SCORE = { low: 1, high: 5 };
const DISTINCTNESS_SCORE = { low: 1, mid: 3, high: 5 };

beforeEach(() => {
  chat.mockReset();
  findOne.mockReset();
  enrichCourseDetail.mockReset();
  loadOrderedVariantsForAssessment.mockReset();

  const course = { id: 3, coreCourseId: 'cuid-core-course' };
  findOne.mockResolvedValue({ id: 10, courseId: 3, course });
  enrichCourseDetail.mockResolvedValue({ id: 3, coreCourseId: 'cuid-core-course', code: 'COSC 121' });
  loadOrderedVariantsForAssessment.mockResolvedValue([
    { id: 1, questionText: 'Q?', answer: 'A', choices: [] },
  ]);
});

describe.each(rows.map((row, index) => ({ row, index })))(
  'ai-judge-scoring PICT row #$index',
  ({ row }) => {
    it('matches the oracle', async () => {
      chat.mockResolvedValue({
        content: JSON.stringify({
          conceptual_equivalence: LEVEL_SCORE[row.ConceptualEquivalence],
          difficulty_similarity: LEVEL_SCORE[row.DifficultySimilarity],
          structural_validity: LEVEL_SCORE[row.StructuralValidity],
          answer_correctness: LEVEL_SCORE[row.AnswerCorrectness],
          topic_alignment: LEVEL_SCORE[row.TopicAlignment],
          distinctness: DISTINCTNESS_SCORE[row.Distinctness],
          usability: row.Usability,
          brief_reason: 'Reason',
        }),
      });

      const result = await reviewVariantExamWithAi(42, {
        baselineAssessmentId: 10,
        variantAssessmentId: 11,
        courseId: 3,
        apiKeys: { vllm: { isEnabled: true } },
        includeOverallSummary: false,
        applyUsabilityPenalty: row.ApplyUsabilityPenalty === 'true',
      });

      const expected = aiJudgeScoringOracle(row);
      expect(result.perQuestion[0].exam_variant_composite_score_1to5).toBeCloseTo(expected.composite1to5, 10);
      expect(result.perQuestion[0].exam_variant_composite_score_1to5_usability_adjusted).toBeCloseTo(
        expected.perQuestionUsabilityAdjusted1to5,
        10,
      );
      expect(result.examVariantScoreFinal0to100).toBeCloseTo(expected.examVariantScoreFinal0to100, 8);
    });
  },
);
