/**
 * PICT model (#1188, census docs/PICT_CENSUS.md § S9): `extractQuestionsWithEduAI`
 * (../../src/services/aiService.js:292), reached via the exported
 * `extractQuestionsFromText`. Chunking (`chunkByQuestionBlocks`) is mocked
 * for deterministic chunk count; deduplication
 * (`deduplicateExtractedQuestions`) runs for real.
 *
 * One oracle (tests/models/extract-questions-with-eduai.oracle.ts), one
 * committed row table (tests/models/extract-questions-with-eduai.cases.json,
 * generated by `npm run test:pict:gen` from
 * tests/models/extract-questions-with-eduai.pict).
 */
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const generateQuestions = vi.fn();
const courseFindUnique = vi.fn();
const topicsFindMany = vi.fn();
const enrichCourseDetail = vi.fn();

vi.mock('../../src/services/eduaiService.js', () => ({
  default: { isConfigured: () => true, generateQuestions },
}));

vi.mock('../../src/config/database.js', () => ({
  prisma: {
    course: { findUnique: courseFindUnique },
    topics: { findMany: topicsFindMany },
  },
}));

vi.mock('../../src/services/courseListService.js', () => ({ enrichCourseDetail }));

vi.mock('../../src/services/extractionUtils.js', async (importOriginal) => {
  const actual = await importOriginal();
  return { ...actual, chunkByQuestionBlocks: vi.fn() };
});

const { extractQuestionsFromText } = await import('../../src/services/aiService.js');
const { chunkByQuestionBlocks } = await import('../../src/services/extractionUtils.js');

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../../../../..');
const rows = JSON.parse(
  readFileSync(path.join(repoRoot, 'tests/models/extract-questions-with-eduai.cases.json'), 'utf8'),
);
const { extractQuestionsWithEduAiOracle } = await import(
  path.join(repoRoot, 'tests/models/extract-questions-with-eduai.oracle.ts')
);

const DUPLICATE_CONTENT = 'Duplicate question text appearing in both chunks';

beforeEach(() => {
  generateQuestions.mockReset();
  courseFindUnique.mockReset();
  topicsFindMany.mockReset();
  enrichCourseDetail.mockReset();

  courseFindUnique.mockResolvedValue({ id: 1, coreCourseId: 'cuid-core-course' });
  enrichCourseDetail.mockResolvedValue({ id: 1, coreCourseId: 'cuid-core-course', code: 'COSC 101' });
});

/** Per-attempt resolved values for one chunk's extraction, per ChunkOutcome. */
function planChunkAttempts(outcome, content) {
  if (outcome === 'success') return [[{ content }]];
  if (outcome === 'retry-succeeds') return [[], [{ content }]];
  return [[], []]; // retry-fails: both attempts come up empty
}

describe.each(rows.map((row, index) => ({ row, index })))(
  'extractQuestionsWithEduAI PICT row #$index $row.ChunkCount/$row.Chunk1Outcome/$row.Chunk2Outcome/$row.DuplicateBetweenChunks/$row.TopicsPresent',
  ({ row }) => {
    it('matches the oracle', async () => {
      topicsFindMany.mockResolvedValue(row.TopicsPresent === 'yes' ? [{ id: 1, name: 'Recursion' }] : []);

      const chunk1Content = row.DuplicateBetweenChunks === 'yes' ? DUPLICATE_CONTENT : 'Chunk 1 unique question';
      const chunk2Content = row.DuplicateBetweenChunks === 'yes' ? DUPLICATE_CONTENT : 'Chunk 2 unique question';

      const chunks = row.ChunkCount === 'one' ? ['CHUNK_1_TEXT'] : ['CHUNK_1_TEXT', 'CHUNK_2_TEXT'];
      chunkByQuestionBlocks.mockReturnValue({ chunks, blockCountsPerChunk: chunks.map(() => 1) });

      // The real code only reaches chunk 2 if chunk 1 didn't abort the whole
      // call (retry-fails throws out of the loop) — mirror that here so the
      // mock queue never expects a call that wouldn't actually happen.
      const queue = [...planChunkAttempts(row.Chunk1Outcome, chunk1Content)];
      if (row.ChunkCount === 'two' && row.Chunk1Outcome !== 'retry-fails') {
        queue.push(...planChunkAttempts(row.Chunk2Outcome, chunk2Content));
      }
      let callIndex = 0;
      generateQuestions.mockImplementation(async () => queue[callIndex++]);

      const expected = extractQuestionsWithEduAiOracle(row);

      if (expected.threw) {
        await expect(extractQuestionsFromText('raw text', 1, 'model', {}, {})).rejects.toThrow();
        return;
      }

      const result = await extractQuestionsFromText('raw text', 1, 'model', {}, {});
      expect(result).toHaveLength(expected.count);

      const firstCallArgs = generateQuestions.mock.calls[0][0];
      const promptHasTopics = firstCallArgs.userPromptOverride.includes('Course topics:');
      expect(promptHasTopics).toBe(row.TopicsPresent === 'yes');
    });
  },
);
