import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("/team", "routes/team.tsx"),
  route("/api/auth/*", "routes/api/auth.$.ts"),
  route("/api/courses", "routes/api/courses.$.ts"),
  route("/login", "routes/login.ts"),
  route("/auth/login", "routes/auth/login.tsx"),
  route("/auth/register", "routes/auth/register.tsx"),
  route("/auth/logout", "routes/auth/logout.tsx"),
  route("/dashboard", "routes/dashboard.tsx"),
  route("/chat", "routes/chat.tsx"),
  route("/settings", "routes/settings.tsx"),
  route("/api/chat", "routes/api/chat.ts"),
  route("/api/chats/:chatId", "routes/api/chats.$chatId.ts"),
  route("/courses", "routes/courses.tsx"),
  route("/courses/:courseId", "routes/courses.$courseId.tsx"),
  route("/api/courses/:courseId/materials", "routes/api/courses.materials.$.ts"),
  route("/api/courses/:courseId/topics", "routes/api/courses.topics.$.ts"),
  route(
    "/api/courses/:courseId/topics/:topicId",
    "routes/api/courses.topics.$.ts",
    { id: "routes/api/courses.topics.$:topicId" },
  ),
  route("/api/courses/:id", "routes/api/courses.id.ts"),
  route("/api/questions", "routes/api/questions.ts"),
  route("/api/questions/:id", "routes/api/questions.$id.ts"),
  route("/admin/ai-models", "routes/admin.ai-models.tsx"),
  route("/admin/users", "routes/admin.users.tsx"),
  route("/api/ai-providers/*", "routes/api/ai-providers.$.ts"),
  route("/api/ai-models/*", "routes/api/ai-models.$.ts"),
  route("/api/users/*", "routes/api/users.$.ts"),
  route("/api/ollama-models", "routes/api/ollama-models.ts"),
  route("/api/sessions/validate", "routes/api/sessions.validate.ts"),
] satisfies RouteConfig;
