import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("/team", "routes/team.tsx"),
  route("/api/auth/*", "routes/api/auth.$.ts"),
  route("/api/courses", "routes/api/courses.$.ts"),
  route("/login", "routes/login.ts"),
  route("/auth/login", "routes/auth/login.tsx"),
  route("/auth/register", "routes/auth/register.tsx"),
  route("/auth/logout", "routes/auth/logout.tsx"),
  route("/auth/accept-invitation", "routes/auth/accept-invitation.tsx"),
  route("/dashboard", "routes/dashboard.tsx"),
  route("/onboarding/student-id", "routes/onboarding.student-id.tsx"),
  route("/chat", "routes/chat.tsx"),
  route("/settings", "routes/settings.tsx"),
  route("/api/canvas/*", "routes/api/canvas.$.ts"),
  route("/api/chat", "routes/api/chat.ts"),
  route("/api/assistive-events", "routes/api/assistive-events.ts"),
  route("/api/chats/:chatId", "routes/api/chats.$chatId.ts"),
  route("/courses", "routes/courses.tsx"),
  route("/courses/:courseId", "routes/courses.$courseId.tsx"),
  route("/units/:department/chats", "routes/units.$department.chats.tsx"),
  route("/api/courses/:courseId/materials", "routes/api/courses.materials.$.ts"),
  route("/api/courses/:courseId/re-embed", "routes/api/courses.re-embed.$.ts"),
  route("/api/courses/:courseId/re-embed/:jobId", "routes/api/courses.re-embed.$jobId.ts"),
  route("/api/courses/:courseId/embedding-settings", "routes/api/courses.embedding-settings.$.ts"),
  route("/api/courses/:courseId/topics", "routes/api/courses.topics.$.ts"),
  route("/api/courses/:courseId/chats", "routes/api/courses.chats.$.ts"),
  route("/api/units/:department/chats", "routes/api/units.chats.$.ts"),
  route("/api/courses/:courseId/tas", "routes/api/courses.tas.$.ts"),
  route(
    "/api/courses/:courseId/topics/:topicId",
    "routes/api/courses.topics.$.ts",
    { id: "routes/api/courses.topics.$:topicId" },
  ),
  route("/api/courses/:id/publish", "routes/api/courses.id.publish.ts"),
  route("/api/courses/:id/unpublish", "routes/api/courses.id.unpublish.ts"),
  route("/api/courses/:id", "routes/api/courses.id.ts"),
  route("/api/courses/:id/enrollments", "routes/api/courses.enrollments.ts"),
  route(
    "/api/courses/:id/enrollments/:enrollmentId",
    "routes/api/courses.enrollments.$enrollmentId.ts",
  ),
  route("/api/courses/:id/rag-settings", "routes/api/courses.id.rag-settings.ts"),
  route("/api/questions", "routes/api/questions.ts"),
  route("/api/questions/:id", "routes/api/questions.$id.ts"),
  route("/admin/ai-models", "routes/admin.ai-models.tsx"),
  route("/admin/users", "routes/admin.users.tsx"),
  route("/admin/invitations", "routes/admin.invitations.tsx"),
  route("/admin/bug-reports", "routes/admin.bug-reports.tsx"),
  route("/admin/settings", "routes/admin.settings.tsx"),
  route("/api/ai-providers/*", "routes/api/ai-providers.$.ts"),
  route("/api/ai-models/*", "routes/api/ai-models.$.ts"),
  route("/api/me", "routes/api/me.ts"),
  route("/api/preferences", "routes/api/preferences.ts"),
  route("/api/users/*", "routes/api/users.$.ts"),
  route("/api/invitations", "routes/api/invitations.ts"),
  route("/api/invitations/accept", "routes/api/invitations.accept.ts"),
  route("/api/invitations/:id", "routes/api/invitations.$id.ts"),
  route("/api/ollama-models", "routes/api/ollama-models.ts"),
  route("/api/vllm-models", "routes/api/vllm-models.ts"),
  route("/api/sessions/validate", "routes/api/sessions.validate.ts"),
  route("/api/policies", "routes/api/policies.ts"),
  route("/api/bug-reports", "routes/api/bug-reports.ts"),
  route("/api/admin/bug-reports", "routes/api/admin.bug-reports.ts"),
  route(
    "/api/admin/bug-reports/:id",
    "routes/api/admin.bug-reports.ts",
    { id: "routes/api/admin.bug-reports:id" },
  ),
  route("/api/e2e/promote", "routes/api/e2e.promote.ts"),
] satisfies RouteConfig;
