/**
 * UBC chatbot disclaimer copy (Draft Chatbot Disclaimer Template v2.1).
 * Contact email is configurable per deployment via VITE_CHAT_DISCLAIMER_CONTACT_EMAIL.
 */

export const CHAT_DISCLAIMER_CONTACT_EMAIL =
  import.meta.env.VITE_CHAT_DISCLAIMER_CONTACT_EMAIL?.trim() || "eduai-support@ubc.ca";

export const CHAT_DISCLAIMER_SHORT =
  "This AI chatbot is a convenience tool but may provide information that is inaccurate, incomplete or outdated. All users are responsible for verifying content against official UBC sources before relying on it.";

export const CHAT_DISCLAIMER_LONG_SECTIONS = [
  {
    title: "CHATBOT DISCLAIMER AND TERMS",
    body: `This chatbot relies upon an artificial intelligence large language model that has been developed and is operated by a third party. UBC is not responsible for the design or operation of the chatbot and has no control over how the chatbot stores or otherwise uses your information, including recording your queries and inputs. UBC is making this chatbot accessible to users through this website solely as a convenience to help users locate and cross-reference official UBC resources. Information provided by the chatbot has not been reviewed, approved, or endorsed by UBC. UBC does not guarantee nor make any representations as to the accuracy, reliability, or completeness of the content. Information provided by the chatbot may contain errors, inaccuracies, omissions, or biases, and should be independently verified by you before being relied upon, by reviewing original source material from official UBC sources.

By using this tool, you acknowledge and agree to the following terms:`,
  },
  {
    title: "1. No Official UBC Representation",
    body: "Content generated by this chatbot does not constitute official UBC information, policy, or advice. UBC does not guarantee, endorse, or assume responsibility for the accuracy or completeness of the chatbot's responses.",
  },
  {
    title: "2. Verification of Content",
    body: "You are responsible for independently verifying the accuracy, reliability, and completeness of any content generated by this chatbot before relying on it for any purpose, including academic, professional, or personal decisions.",
  },
  {
    title: "3. Assumption of Risk",
    body: "Any actions you take based on the chatbot's content are at your own risk. UBC is not liable for any consequences arising from your use of this tool or from actions taken or not taken based on its content.",
  },
  {
    title: "4. Privacy and Confidentiality",
    body: "By using this tool, you acknowledge that you may be disclosing information to one or more third-parties who own or operate the chatbot or various components of the chatbot. UBC has no control over how these third parties collect, store, or use information input into the tool. Do not enter any confidential, sensitive, or personally identifiable information.",
  },
  {
    title: "5. Copyright and Intellectual Property",
    body: "The chatbot generates content based on a combination of publicly accessible data, licensed data, and information input by you and other users. The chatbot does not have awareness of which, if any, of those materials are subject to copyright or are otherwise proprietary in nature. The chatbot may fail to cite its sources or give proper attribution. Reproducing material provided to you by the chatbot may result in you breaching copyright or other laws.",
  },
  {
    title: "6. Compliance with Laws",
    body: "Users are responsible for ensuring compliance with all applicable laws when using, sharing, or otherwise acting upon the chatbot's content.",
  },
  {
    title: "7. Reporting of Inappropriate Content",
    body: `The chatbot may produce offensive, biased, or otherwise inappropriate content. Although UBC is not responsible for the operation of the chatbot, we do request that you report it to ${CHAT_DISCLAIMER_CONTACT_EMAIL} if you encounter content of this nature, so that UBC can inform the chatbot's developer as appropriate.`,
  },
] as const;

export const CHAT_DISCLAIMER_CLOSING =
  "By using this chatbot, you agree to these terms and disclaimers, acknowledging the tool's limitations and potential risks.";
