import { z } from 'zod';

export const UNITS = [
  'ANTH',
  'APSC',
  'ARTH',
  'ASTR',
  'BIOC',
  'BIOL',
  'BTEC',
  'CHEM',
  'CHIN',
  'CMPE',
  'COMM',
  'COSC',
  'COOP',
  'CCS',
  'CORH',
  'CRWR',
  'CULT',
  'CUST',
  'DATA',
  'DICE',
  'DIHU',
  'EADM',
  'ECED',
  'ECON',
  'EDLL',
  'EDST',
  'EDUC',
  'EESC',
  'ENGR',
  'ENGL',
  'EAP',
  'EPSE',
  'ETEC',
  'EXCH',
  'FDSY',
  'FILM',
  'FREN',
  'FWSC',
  'GEOG',
  'GERM',
  'GISC',
  'GWST',
  'HEAL',
  'HEBR',
  'HES',
  'HINT',
  'HIST',
  'IGS',
  'IMTC',
  'INDG',
  'INLG',
  'JPST',
  'KORN',
  'LATN',
  'LLED',
  'MANF',
  'MATH',
  'MDST',
  'MGMT',
  'MUSC',
  'NLEK',
  'NRSG',
  'NSYL',
  'PHIL',
  'PHYS',
  'PDHC',
  'POLI',
  'PSYO',
  'SCIE',
  'SECW',
  'SOCI',
  'SOCW',
  'SPAN',
  'STAT',
  'STMC',
  'SUST',
  'THTR',
  'VANT',
  'VISA',
  'WRLD',
] as const;

export const UnitSchema = z.enum(UNITS);
export type Unit = z.infer<typeof UnitSchema>;

export const UNIT_LABELS: Record<Unit, string> = {
  ANTH: 'Anthropology',
  APSC: 'Applied Science',
  ARTH: 'Art History and Visual Culture',
  ASTR: 'Astronomy',
  BIOC: 'Biochemistry',
  BIOL: 'Biology',
  BTEC: 'Biotechnology',
  CHEM: 'Chemistry',
  CHIN: 'Chinese',
  CMPE: 'Computer Engineering',
  COMM: 'Commerce',
  COSC: 'Computer Science',
  COOP: 'Cooperative Education',
  CCS: 'Creative and Critical Studies',
  CORH: 'Communications and Rhetoric',
  CRWR: 'Creative Writing',
  CULT: 'Cultural Studies',
  CUST: 'Curriculum Studies',
  DATA: 'Data Science',
  DICE: 'Design, Innovation, Creativity, Entrepreneurship',
  DIHU: 'Digital Humanities',
  EADM: 'Educational Administration',
  ECED: 'Early Childhood Education',
  ECON: 'Economics',
  EDLL: 'Education Doctorate Leadership and Learning',
  EDST: 'Educational Studies',
  EDUC: 'Education',
  EESC: 'Earth and Environmental Sciences',
  ENGR: 'Engineering',
  ENGL: 'English',
  EAP: 'English for Academic Purposes',
  EPSE: 'Educational Psychology and Special Education',
  ETEC: 'Educational Technology',
  EXCH: 'Exchange Programs',
  FDSY: 'Food Systems',
  FILM: 'Film',
  FREN: 'French',
  FWSC: 'Freshwater Science',
  GEOG: 'Geography',
  GERM: 'German',
  GISC: 'Geospatial Information Science',
  GWST: 'Gender, Women and Sexuality Studies',
  HEAL: 'Health Studies',
  HEBR: 'Hebrew',
  HES: 'Health and Exercise Sciences',
  HINT: 'Health Interprofessional',
  HIST: 'History',
  IGS: 'Interdisciplinary Graduate Studies',
  IMTC: 'Immersive Technologies',
  INDG: 'Indigenous Studies',
  INLG: 'Indigenous Language',
  JPST: 'Japanese Studies',
  KORN: 'Korean',
  LATN: 'Latin',
  LLED: 'Language and Literacy Education',
  MANF: 'Manufacturing Engineering',
  MATH: 'Mathematics',
  MDST: 'Media Studies',
  MGMT: 'Management',
  MUSC: 'Music',
  NLEK: 'Nle?kepmx Language',
  NRSG: 'Nursing',
  NSYL: 'Nsyilxcn',
  PHIL: 'Philosophy',
  PHYS: 'Physics',
  PDHC: 'Product Design for Human Comfort',
  POLI: 'Political Science',
  PSYO: 'Psychology',
  SCIE: 'Science',
  SECW: 'Secwépemc',
  SOCI: 'Sociology',
  SOCW: 'Social Work',
  SPAN: 'Spanish',
  STAT: 'Statistics',
  STMC: "St'át'imc Language",
  SUST: 'Sustainability',
  THTR: 'Theatre',
  VANT: 'Vantage College',
  VISA: 'Visual Arts',
  WRLD: 'World Literature',
};

export function getDepartmentLabel(code: string): string {
  return UNIT_LABELS[code as Unit] ?? code;
}

export const UNIT_OPTIONS = UNITS.map((code) => ({
  code,
  label: UNIT_LABELS[code],
}));
