// @vitest-environment node
//
// PICT drift-contract pilot (#1180, census docs/PICT_CENSUS.md § S1): the same
// student-visibility rule is enforced independently in three places — the REST
// material read gate (routes/api/courses.materials.$.ts) and both RAG
// retrieval branches in lib/ai/embedding.ts (hybrid BM25 and pure vector). One
// oracle (tests/models/material-visibility.oracle.ts), one committed row table
// (tests/models/material-visibility.cases.json, generated by
// `npm run test:pict:gen` from tests/models/material-visibility.pict), and one
// world-builder per row here — each row is routed to whichever path it names.
//
// Real Postgres + pgvector. Only the embedding provider network call is
// mocked, with a fixed vector reused for both the seeded chunk and every
// query — cosine similarity is always 1, so the RAG assertions test the SQL
// visibility WHERE-clauses, never similarity ranking.

import { describe, it, expect, vi, beforeAll, beforeEach, afterAll } from "vitest";
import prisma from "~/lib/prisma.server";

vi.mock("~/lib/auth/server", () => ({
  auth: { api: { getSession: vi.fn() } },
}));

const EMBEDDING_DIMENSION = 1024;
const FIXED_EMBEDDING = vi.hoisted(() =>
  Array.from({ length: 1024 }, (_, i) => (i + 1) * 0.0001),
);

vi.mock("ai", () => ({
  embed: vi.fn().mockResolvedValue({ embedding: FIXED_EMBEDDING }),
  embedMany: vi.fn(),
}));
vi.mock("@ai-sdk/openai", () => ({
  createOpenAI: vi.fn(() => ({ embedding: vi.fn(() => ({})) })),
}));
vi.mock("@ai-sdk/google", () => ({ createGoogleGenerativeAI: vi.fn() }));
vi.mock("ollama-ai-provider", () => ({ createOllama: vi.fn() }));

import { loader } from "~/routes/api/courses.materials.$";
import { findRelevantContent } from "~/lib/ai/embedding";
import { resolveCourseAccessWithCourse } from "~/lib/auth/course-access.server";
import { seedUser, seedCourse, enroll, mockSession, cleanupRbac } from "../helpers/rbac";
import { seedMaterial, seedMaterialChunkWithEmbedding } from "../helpers/materials";
import { seedTestDisciplines } from "../helpers/disciplines";
import materialVisibilityCases from "../../../../../tests/models/material-visibility.cases.json";
import {
  expectedRestStatus,
  expectedRagIncluded,
  type MaterialVisibilityRow,
} from "../../../../../tests/models/material-visibility.oracle";

const rows = materialVisibilityCases as MaterialVisibilityRow[];

// This model has no UnitMatch dimension (unlike the S2 flagship model) — every
// UNIT_ADMIN row is built with its unit matching this department, so the
// staff-bypass verdict always holds. COSC is one of the seeded test disciplines
// (helpers/disciplines.ts) — `department` is an FK to Discipline.code.
const DEPARTMENT = "COSC";

const ENROLLMENT_ROLE: Partial<Record<MaterialVisibilityRow["Role"], "INSTRUCTOR" | "TA" | "STUDENT">> = {
  INSTRUCTOR: "INSTRUCTOR",
  TA: "TA",
  STUDENT: "STUDENT",
};

type SeededRow = {
  courseId: string;
  materialId: string;
  user: { id: string; role: string } | null;
};

const seededUserIds: string[] = [];
const seededCourseIds: string[] = [];

/** World-builder: (row) => seeded state. Extends helpers/rbac.ts + helpers/materials.ts. */
async function buildRow(row: MaterialVisibilityRow): Promise<SeededRow> {
  const course = await seedCourse({ isPublished: true, department: DEPARTMENT });
  seededCourseIds.push(course.id);

  const availableAt =
    row.AvailableAt === "past"
      ? new Date(Date.now() - 60_000)
      : row.AvailableAt === "future"
        ? new Date(Date.now() + 60 * 60_000)
        : null;
  const deletedAt = row.Deleted === "yes" ? new Date() : null;

  const material = await seedMaterial({
    courseId: course.id,
    visibleToStudents: row.VisibleToStudents === "true",
    availableAt,
    deletedAt,
  });
  await seedMaterialChunkWithEmbedding(material.id, FIXED_EMBEDDING);

  let user: { id: string; role: string } | null = null;

  if (row.Role === "ANON") {
    user = null;
  } else if (row.Role === "ADMIN") {
    user = await seedUser({ role: "ADMIN" });
    seededUserIds.push(user.id);
  } else if (row.Role === "UNIT_ADMIN") {
    user = await seedUser({ role: "UNIT_ADMIN", authorizedUnits: [DEPARTMENT] });
    seededUserIds.push(user.id);
  } else {
    // INSTRUCTOR/TA/STUDENT are enrollment roles, not platform roles (#292
    // family convention) — platform role is irrelevant to access resolution
    // below ADMIN/UNIT_ADMIN, so seed a plain STUDENT account.
    user = await seedUser({ role: "STUDENT" });
    seededUserIds.push(user.id);
    if (row.Enrolled === "yes") {
      await enroll(course.id, user.id, ENROLLMENT_ROLE[row.Role]!);
    }
  }

  return { courseId: course.id, materialId: material.id, user };
}

// Force the cloud embedding branch so the mocked "ai"/"@ai-sdk/openai" modules
// above are actually what generateEmbedding() calls — apps/core/.env defaults
// EMBEDDING_PROVIDER to "local" (Ollama) for real dev use, which would
// otherwise try a real network call here.
const ORIGINAL_ENV = {
  EMBEDDING_PROVIDER: process.env.EMBEDDING_PROVIDER,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OLLAMA_BASE_URL: process.env.OLLAMA_BASE_URL,
  EMBEDDING_DIMENSION: process.env.EMBEDDING_DIMENSION,
};

beforeAll(async () => {
  await seedTestDisciplines();
  process.env.EMBEDDING_PROVIDER = "cloud";
  process.env.OPENAI_API_KEY = "test-key";
  process.env.EMBEDDING_DIMENSION = String(EMBEDDING_DIMENSION);
  delete process.env.OLLAMA_BASE_URL;
});

afterAll(async () => {
  await cleanupRbac({ userIds: seededUserIds, courseIds: seededCourseIds });
  await prisma.$disconnect();
  for (const [key, value] of Object.entries(ORIGINAL_ENV)) {
    if (value === undefined) delete process.env[key];
    else process.env[key] = value;
  }
});

beforeEach(() => {
  mockSession(null);
  delete process.env.RAG_HYBRID_BM25;
});

async function assertRest(row: MaterialVisibilityRow, seeded: SeededRow) {
  mockSession(seeded.user);
  const response = await loader({
    request: new Request(
      `http://localhost/api/courses/${seeded.courseId}/materials/${seeded.materialId}`,
    ),
    params: { courseId: seeded.courseId, materialId: seeded.materialId },
    context: {} as never,
  } as any);
  expect(response.status).toBe(expectedRestStatus(row));
}

/**
 * RAG adapter for both `rag-hybrid` and `rag-sql`: `RAG_HYBRID_BM25` selects
 * the branch inside `findRelevantContent` (embedding.ts:664); the caller-side
 * access resolution mirrors routes/api/chat.ts's real gate (resolve course
 * access, then only query RAG at all if that gate is open) via the same
 * production `resolveCourseAccessWithCourse`, not a re-implementation of it.
 */
async function assertRag(row: MaterialVisibilityRow, seeded: SeededRow) {
  process.env.RAG_HYBRID_BM25 = row.Path === "rag-hybrid" ? "1" : "";

  if (!seeded.user) {
    throw new Error("ANON rows are constrained to Path=rest by the model — world-builder bug");
  }

  const { course, access } = await resolveCourseAccessWithCourse(seeded.user, seeded.courseId);
  const gateOpen = course !== null && access !== null && !(access.level === "student" && !course.isPublished);

  const hits = gateOpen
    ? await findRelevantContent(
        "seeded PICT query",
        seeded.courseId,
        10,
        undefined,
        access!.level === "student",
      )
    : [];

  expect(hits.length > 0).toBe(expectedRagIncluded(row));
}

describe.each(rows.map((row, index) => ({ row: row as MaterialVisibilityRow, index })))(
  "material-visibility PICT row #$index $row.Role/$row.Enrolled/$row.VisibleToStudents/$row.AvailableAt/$row.Deleted/$row.Path",
  ({ row }) => {
    it(`matches the oracle verdict on ${row.Path}`, async () => {
      const seeded = await buildRow(row);
      if (row.Path === "rest") {
        await assertRest(row, seeded);
      } else {
        await assertRag(row, seeded);
      }
    });
  },
);
