// ── Utilities ─────────────────────────────────────────────────────────────
export { cn, getInitials } from "./utils"

// ── Theme ──────────────────────────────────────────────────────────────────
export { ThemeProvider, useTheme } from "./theme-provider"
export { initThemeSync, broadcastThemeChange, closeThemeSync } from "./lib/theme-sync"
export type { Theme as ThemeType } from "./lib/theme-sync"

// ── Domain components ──────────────────────────────────────────────────────
export { RoleBadge } from "./role-badge"
export type { RoleBadgeProps } from "./role-badge"
export { CourseColorBar, COURSE_COLORS } from "./course-color-bar"
export type { CourseColorBarProps } from "./course-color-bar"
export { StatCard } from "./stat-card"
export type { StatCardProps } from "./stat-card"
export { Avatar } from "./avatar"
export type { AvatarProps } from "./avatar"
export { PageHeading } from "./page-heading"
export type { PageHeadingProps } from "./page-heading"
export { CourseHeroCard } from "./course-hero-card"
export type { CourseHeroCardProps } from "./course-hero-card"
export { CourseCard } from "./course-card"
export type { CourseCardProps, CourseCardAction } from "./course-card"
export { StatusBadge } from "./status-badge"
export type { StatusBadgeProps } from "./status-badge"
export { PageTabs, PageTabsList, PageTabsTrigger, PageTabsContent } from "./page-tabs"
export type { PageTabsProps, PageTabsListProps, PageTabsTriggerProps, PageTabsContentProps } from "./page-tabs"

// ── DS-aligned shadcn primitives ───────────────────────────────────────────
export { Button, buttonVariants } from "./ui/button"
export { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter, CardAction } from "./ui/card"
export { Badge, badgeVariants } from "./ui/badge"
export { Input } from "./ui/input"

// ── shadcn primitives ──────────────────────────────────────────────────────
export * from "./ui/accordion"
export * from "./ui/alert"
export * from "./ui/alert-dialog"
export * from "./ui/aspect-ratio"
// Avatar: export AvatarImage/AvatarFallback only — Avatar root conflicts with DS Avatar above
export { AvatarImage, AvatarFallback } from "./ui/avatar"
export * from "./ui/breadcrumb"
export * from "./ui/calendar"
export * from "./ui/carousel"
export * from "./ui/chart"
export * from "./ui/chat-container"
export * from "./ui/checkbox"
export * from "./ui/code-block"
export * from "./ui/collapsible"
export * from "./ui/command"
export * from "./ui/context-menu"
export * from "./ui/dialog"
export * from "./ui/drawer"
export * from "./ui/dropdown-menu"
export * from "./ui/form"
export * from "./ui/hover-card"
export * from "./ui/input-otp"
export * from "./ui/label"
export * from "./ui/loader"
export * from "./ui/markdown"
export { streamdownPlugins } from "./ui/streamdown-config"
export * from "./ui/menubar"
export * from "./ui/navigation-menu"
export * from "./ui/pagination"
export * from "./ui/popover"
export * from "./ui/progress"
export * from "./ui/prompt-input"
export * from "./ui/prompt-suggestion"
export * from "./ui/radio-group"
export * from "./ui/resizable"
export * from "./ui/response-stream"
export * from "./ui/scroll-area"
export * from "./ui/scroll-button"
export * from "./ui/select"
export * from "./ui/separator"
export * from "./ui/sheet"
export * from "./ui/skeleton"
export * from "./ui/slider"
export * from "./ui/sonner"
export * from "./ui/switch"
export * from "./ui/table"
export * from "./ui/tabs"
export * from "./ui/textarea"
export * from "./ui/toggle"
export * from "./ui/toggle-group"
export * from "./ui/tool"
export * from "./ui/tooltip"
export * from "./ui/sidebar"
export * from "./ui/message"
export { useIsMobile } from "./hooks/use-mobile"
export { Combobox, MultiSelect } from "./ui/combobox"
export type { ComboboxOption, ComboboxProps, MultiSelectProps } from "./ui/combobox"
