// PICT drift-contract (#1187, census docs/PICT_CENSUS.md § S8): the same
// `hasElevatedAccess = isAdmin || isInstructor || isTa || isUnitAdmin`
// formula is written independently in routes/activities.js
// (GET /lessons/:lessonId/activities) and routes/modules.js
// (GET /courses/:courseId/modules). One oracle
// (tests/models/lesson-modules-view.oracle.ts), one committed row table
// (tests/models/lesson-modules-view.cases.json, generated by
// `npm run test:pict:gen` from tests/models/lesson-modules-view.pict), and
// one world-builder here — each row is exercised against both routes.
//
// Real Postgres via the ai-tutor Prisma client + a real Express app
// (createApp). Only the Core department lookup (fetchCoreCourseSafe, used by
// isUnitAdminForCourse) is mocked; ANON rows go through createApp()'s real
// auth middleware, which fails closed to 401 when Core is unreachable.

import { describe, it, expect, beforeEach, vi } from 'vitest';
import request from 'supertest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { createApp } from '../../src/app.js';
import {
  makeProfessor,
  makeStudent,
  makeAdmin,
  makeTA,
  makeUnitAdmin,
  truncateAll,
  seedMinimalCourse,
  prisma,
} from '../helpers.js';

vi.mock('../../src/services/eduaiClient.js', async (importOriginal) => {
  const actual = await importOriginal();
  return { ...actual, fetchCoreCourseSafe: vi.fn() };
});

import { fetchCoreCourseSafe } from '../../src/services/eduaiClient.js';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../../../..');
const rows = JSON.parse(
  readFileSync(path.join(repoRoot, 'tests/models/lesson-modules-view.cases.json'), 'utf8'),
);
const {
  expectedActivitiesListStatus,
  expectedModulesListStatus,
  expectedModuleVisibleInList,
} = await import(path.join(repoRoot, 'tests/models/lesson-modules-view.oracle.ts'));

const DEPARTMENT = 'COSC';
const NOT_FOUND_ID = 999_999_999;

beforeEach(async () => {
  await truncateAll();
  vi.mocked(fetchCoreCourseSafe).mockImplementation(async (coreOfferingId) => ({
    id: coreOfferingId,
    department: DEPARTMENT,
  }));
});

/**
 * World-builder: (row) => a course/module/lesson seeded with Published on
 * both module and lesson, plus a caller app whose user has exactly the
 * relationship to the course that Role names.
 */
async function buildRow(row) {
  const owner = makeProfessor();
  const seed = await seedMinimalCourse(owner.id);
  await prisma.module.update({ where: { id: seed.module.id }, data: { isPublished: row.Published === 'yes' } });
  await prisma.lesson.update({ where: { id: seed.lesson.id }, data: { isPublished: row.Published === 'yes' } });

  let app;
  switch (row.Role) {
    case 'ANON':
      app = await createApp();
      break;
    case 'ADMIN':
      app = await createApp({ mockUser: makeAdmin() });
      break;
    case 'INSTRUCTOR': {
      // seedMinimalCourse already made `owner` this course's instructor.
      app = await createApp({ mockUser: owner });
      break;
    }
    case 'TA': {
      const ta = makeTA();
      await prisma.courseEnrollment.create({ data: { courseOfferingId: seed.course.id, userId: ta.id, role: 'TA' } });
      app = await createApp({ mockUser: ta });
      break;
    }
    case 'UNIT_ADMIN': {
      const unitAdmin = makeUnitAdmin([DEPARTMENT]);
      app = await createApp({ mockUser: unitAdmin });
      break;
    }
    case 'STUDENT': {
      const student = makeStudent();
      await prisma.courseEnrollment.create({
        data: { courseOfferingId: seed.course.id, userId: student.id, role: 'STUDENT' },
      });
      app = await createApp({ mockUser: student });
      break;
    }
    case 'NONE': {
      const stranger = makeProfessor(); // authenticated, but not this course's instructor and not enrolled
      app = await createApp({ mockUser: stranger });
      break;
    }
  }

  const lessonId = row.Found === 'yes' ? seed.lesson.id : NOT_FOUND_ID;
  const courseId = row.Found === 'yes' ? seed.course.id : NOT_FOUND_ID;
  return { app, lessonId, courseId, moduleId: seed.module.id };
}

describe.each(rows.map((row, index) => ({ row, index })))(
  'lesson-modules-view PICT row #$index $row.Role/$row.Published/$row.Found',
  ({ row }) => {
    it('activities route matches the oracle', async () => {
      const { app, lessonId } = await buildRow(row);
      const res = await request(app).get(`/api/lessons/${lessonId}/activities`);
      expect(res.status).toBe(expectedActivitiesListStatus(row));
    });

    it('modules route matches the oracle, including list-filtering vs 403', async () => {
      const { app, courseId, moduleId } = await buildRow(row);
      const res = await request(app).get(`/api/courses/${courseId}/modules`);
      expect(res.status).toBe(expectedModulesListStatus(row));

      const expectedVisible = expectedModuleVisibleInList(row);
      if (expectedVisible !== null) {
        const visible = res.body.data.some((m) => m.id === moduleId);
        expect(visible).toBe(expectedVisible);
      }
    });
  },
);
