// PICT drift-contract (#1187, census docs/PICT_CENSUS.md § S8): the same
// "is this activity counted, and is it complete" rule is computed
// independently by calculateCourseProgress, calculateModuleProgress, and
// calculateLessonProgress (../../src/services/progressCalculation.js). One
// oracle (tests/models/progress-denominators.oracle.ts), one committed row
// table (tests/models/progress-denominators.cases.json, generated by
// `npm run test:pict:gen` from tests/models/progress-denominators.pict), and
// one world-builder here — each row is exercised against all three
// functions, so divergence between them on the same input is visible in a
// single assertion's failure output, not just divergence from the oracle.
//
// Real Postgres via the ai-tutor Prisma client. No network calls.

import { describe, it, expect, beforeEach } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { makeProfessor, makeStudent, truncateAll, seedMinimalCourse, prisma } from '../helpers.js';
import {
  calculateCourseProgress,
  calculateModuleProgress,
  calculateLessonProgress,
} from '../../src/services/progressCalculation.js';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../../../..');
const rows = JSON.parse(
  readFileSync(path.join(repoRoot, 'tests/models/progress-denominators.cases.json'), 'utf8'),
);
const { expectedResult } = await import(
  path.join(repoRoot, 'tests/models/progress-denominators.oracle.ts')
);

beforeEach(async () => {
  await truncateAll();
});

/**
 * World-builder: (row) => a single course/module/lesson/activity, with
 * lesson.isPublished and module.isPublished set per row, plus a submission
 * history for one student matching row.AttemptPattern.
 */
async function buildRow(row) {
  const prof = makeProfessor();
  const seed = await seedMinimalCourse(prof.id);
  const student = makeStudent();
  await prisma.courseEnrollment.create({
    data: { courseOfferingId: seed.course.id, userId: student.id },
  });

  await prisma.module.update({
    where: { id: seed.module.id },
    data: { isPublished: row.ModulePublished === 'yes' },
  });
  await prisma.lesson.update({
    where: { id: seed.lesson.id },
    data: { isPublished: row.LessonPublished === 'yes' },
  });

  const activity = await prisma.activity.create({
    data: {
      lessonId: seed.lesson.id,
      mainTopicId: seed.topic.id,
      instructionsMd: 'Instructions',
      config: { question: 'Q?', questionType: 'MCQ' },
      position: 0,
    },
  });

  const attempts = {
    not_attempted: [],
    correct_only: [[1, true]],
    incorrect_only: [[1, false]],
    correct_then_incorrect: [
      [1, true],
      [2, false],
    ],
    incorrect_then_correct: [
      [1, false],
      [2, true],
    ],
  }[row.AttemptPattern];

  for (const [attemptNumber, isCorrect] of attempts) {
    await prisma.submission.create({
      data: { userId: student.id, activityId: activity.id, attemptNumber, isCorrect, response: {} },
    });
  }

  return { courseId: seed.course.id, moduleId: seed.module.id, lessonId: seed.lesson.id, userId: student.id };
}

describe.each(rows.map((row, index) => ({ row, index })))(
  'progress-denominators PICT row #$index $row.LessonPublished/$row.ModulePublished/$row.AttemptPattern',
  ({ row }) => {
    it('course, module, and lesson scope all agree with the oracle and with each other', async () => {
      const seeded = await buildRow(row);
      const expected = expectedResult(row);

      const [course, module, lesson] = await Promise.all([
        calculateCourseProgress(seeded.courseId, seeded.userId),
        calculateModuleProgress(seeded.moduleId, seeded.userId),
        calculateLessonProgress(seeded.lessonId, seeded.userId),
      ]);

      expect({ course, module, lesson }).toEqual({ course: expected, module: expected, lesson: expected });
    });
  },
);
