// PICT model (#1188, census docs/PICT_CENSUS.md § S9): `validateContextAndAccess`
// (../../src/services/bugReports.js), reached via the exported
// `createBugReport`. Checks hierarchy existence, then internal consistency,
// then role, then content-aware authorization, in that order.
//
// One oracle (tests/models/validate-context-and-access.oracle.ts), one
// committed row table (tests/models/validate-context-and-access.cases.json,
// generated by `npm run test:pict:gen` from
// tests/models/validate-context-and-access.pict), and one world-builder
// here. `validateContextAndAccess` itself isn't exported, so this exercises
// it through `createBugReport` (the only exported entry point that calls it)
// with the outbound Core call (`postCoreBugReport`) mocked.
//
// Real Postgres via the ai-tutor Prisma client.

import { describe, it, expect, beforeEach, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { makeProfessor, makeStudent, makeAdmin, truncateAll, seedMinimalCourse, prisma } from '../helpers.js';

vi.mock('../../src/services/eduaiClient.js', async (importOriginal) => {
  const actual = await importOriginal();
  return { ...actual, postCoreBugReport: vi.fn().mockResolvedValue({ ok: true }) };
});

import { createBugReport, BugReportError } from '../../src/services/bugReports.js';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../../../..');
const rows = JSON.parse(
  readFileSync(path.join(repoRoot, 'tests/models/validate-context-and-access.cases.json'), 'utf8'),
);
const { validateContextAndAccessOracle } = await import(
  path.join(repoRoot, 'tests/models/validate-context-and-access.oracle.ts')
);

const MISSING_ID = 999_999_999;

beforeEach(async () => {
  await truncateAll();
});

/**
 * World-builder: two independent course/module/lesson/activity chains
 * (A = the "real" one, B = a foreign branch used to source a mismatched
 * parent id for Consistency="inconsistent"), plus a caller with exactly
 * Role/Authorized, and a `context` payload built per ContextDepth/Existence/
 * Consistency.
 */
async function buildRow(row) {
  const profA = makeProfessor();
  const seedA = await seedMinimalCourse(profA.id);
  const activityA = await prisma.activity.create({
    data: {
      lessonId: seedA.lesson.id,
      mainTopicId: seedA.topic.id,
      instructionsMd: 'Instructions',
      config: { question: 'Q?', questionType: 'MCQ' },
    },
  });

  const profB = makeProfessor();
  const seedB = await seedMinimalCourse(profB.id);

  let context;
  if (row.ContextDepth === 'none') {
    context = undefined;
  } else if (row.ContextDepth === 'course') {
    context = { courseOfferingId: row.Existence === 'missing' ? MISSING_ID : seedA.course.id };
  } else if (row.ContextDepth === 'module') {
    context = {
      courseOfferingId: row.Consistency === 'inconsistent' ? seedB.course.id : seedA.course.id,
      moduleId: row.Existence === 'missing' ? MISSING_ID : seedA.module.id,
    };
  } else if (row.ContextDepth === 'lesson') {
    context = {
      courseOfferingId: seedA.course.id,
      moduleId: row.Consistency === 'inconsistent' ? seedB.module.id : seedA.module.id,
      lessonId: row.Existence === 'missing' ? MISSING_ID : seedA.lesson.id,
    };
  } else {
    context = {
      courseOfferingId: seedA.course.id,
      moduleId: seedA.module.id,
      lessonId: row.Consistency === 'inconsistent' ? seedB.lesson.id : seedA.lesson.id,
      activityId: row.Existence === 'missing' ? MISSING_ID : activityA.id,
    };
  }

  let user;
  switch (row.Role) {
    case 'STUDENT': {
      const student = makeStudent();
      if (row.Authorized === 'yes') {
        await prisma.courseEnrollment.create({
          data: { courseOfferingId: seedA.course.id, userId: student.id, role: 'STUDENT' },
        });
      }
      user = student;
      break;
    }
    case 'INSTRUCTOR':
      user = row.Authorized === 'yes' ? profA : profB; // profB instructs seedB, not seedA
      break;
    case 'OTHER':
      user = makeAdmin();
      break;
  }

  return { user, context };
}

describe.each(rows.map((row, index) => ({ row, index })))(
  'validateContextAndAccess PICT row #$index $row.ContextDepth/$row.Existence/$row.Consistency/$row.Role/$row.Authorized',
  ({ row }) => {
    it('matches the oracle', async () => {
      const { user, context } = await buildRow(row);
      const payload = { description: 'A sufficiently long bug description.', context };
      const expected = validateContextAndAccessOracle(row);

      if (expected.ok) {
        await expect(createBugReport(user, payload)).resolves.toBeUndefined();
      } else {
        let error;
        try {
          await createBugReport(user, payload);
        } catch (e) {
          error = e;
        }
        expect(error).toBeInstanceOf(BugReportError);
        expect(error.status).toBe(expected.status);
      }
    });
  },
);
