# Playwright E2E test runner
#
# Build context: monorepo root

FROM mcr.microsoft.com/playwright:v1.50.1-jammy

WORKDIR /e2e

COPY tests/e2e/package.json ./
RUN npm install

COPY tests/e2e/ ./

CMD ["npx", "playwright", "test"]