model_list:
  - model_name: qwen3.5-2b
    litellm_params:
      model: openai/qwen3.5-2b
      api_base: http://127.0.0.1:18001/v1
      api_key: os.environ/VLLM_API_KEY

  - model_name: qwen3.5-27b
    litellm_params:
      model: openai/qwen3.5-27b
      api_base: http://127.0.0.1:18002/v1
      api_key: os.environ/VLLM_API_KEY

general_settings:
  master_key: os.environ/VLLM_API_KEY
